name: WordPress Deployment

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Dev Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-18-118-111-222.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html 
            git pull origin main
            ls -nat
